name: Kill some tweets!

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  kill-some-tweets:
    name: Tweet Killer, qu'est-ce que c'est
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.5-stretch
    steps:
      - name: Install dependencies
        run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - name: Delete tweets
        run: ruby twitter_delete.rb --user spooneybarger --days 10 --rts 2 --favs 2 --force
